### ISSUE TITLE
Document Public Class/Method is a Smell?

### ISSUE THREAD

**Issue by mikesmithson** [QualInsight/qualinsight-plugins-sonarqube-smell#45]
I had run a SonarQube analysis and I got a code smell violation of undocumented public class/method. Since my application does not need to have a public api, why would I need to Javadoc every class/method if it adds no value, is unnecessary, and adds more noise to my source code?

**Comment by pawlakm** [comment]
Your question has nothing to do with the Code Smells plugin. It is related to SonarQube's Java plugin. You should therefore complain directly on SonarQube's Google group.

You've been mistaken by the fact that since version 5.5 SonarQube categorises issues using the names "vulnerabilities", "bugs" and "code smells"... as you can see the name of this last category clashes with the name of my plugin. You'll find [my opinion on SonarQube's on Google group](https://groups.google.com/d/msg/sonarqube/I-8gq3P81MI/qN4aVHwrAwAJ) about their usage of the "code smell" concept and why I think that their categories are wrongly / poorly named... You can read it as well as the [documentation of this plugin](https://github.com/QualInsight/qualinsight-plugins-sonarqube-smell) to better understand what a code smell really is.

By the way, this plugin is using this name since August 2015, they started to (poorly) use the "code smell" concept in April 2016.

Now if you want my opinion about your question, it is simple: you should read "clean code".

**Comment by mikesmithson** [comment]
Thanks for the clarification. I think that we are on the same page as far as what is/isn't a code smell. I am all about clean code and software craftsmanship, read "Clean Code" and even work in the same group as one of the authors of that book. Thanks again...
